2017-06-29 11:18:14.638 +08:00 [Information] "Host","20022","e:\picsig","e:\piclog","e:\pic"------------------------------------
2017-06-29 11:18:19.635 +08:00 [Information] Request starting HTTP/1.1 GET http://localhost:5000/  
2017-06-29 11:18:21.715 +08:00 [Information] Request finished in 2501.7773ms 404 
2017-06-29 11:18:21.987 +08:00 [Information] Request starting HTTP/1.1 GET http://localhost:5000/  
2017-06-29 11:18:22.021 +08:00 [Information] Request starting HTTP/1.1 GET http://localhost:5000/favicon.ico  
2017-06-29 11:18:22.134 +08:00 [Information] Request finished in 147.6002ms 404 
2017-06-29 11:18:22.151 +08:00 [Information] Request starting HTTP/1.1 GET http://localhost:5000/favicon.ico  
2017-06-29 11:18:22.229 +08:00 [Information] Request finished in 209.0326ms 404 
2017-06-29 11:18:22.409 +08:00 [Information] Request starting HTTP/1.1 GET http://localhost:5000/favicon.ico  
2017-06-29 11:18:22.424 +08:00 [Information] Request finished in 15.1393ms 404 
2017-06-29 11:18:22.425 +08:00 [Information] Request finished in 274.3032ms 404 
2017-06-29 11:18:24.461 +08:00 [Information] Request starting HTTP/1.1 GET http://localhost:5000/yonghuxuzhi  
2017-06-29 11:18:24.611 +08:00 [Information] Executing action method "study.Controllers.ValuesController.yonghuxuzhi (study)" with arguments (null) - ModelState is Valid
2017-06-29 11:18:28.072 +08:00 [Information] Executing ViewResult, running view at path "/Views/Values/yonghuxuzhi.cshtml".
2017-06-29 11:18:28.243 +08:00 [Information] User profile is available. Using '"C:\Users\Administrator\AppData\Local\ASP.NET\DataProtection-Keys"' as key repository and Windows DPAPI to encrypt keys at rest.
2017-06-29 11:18:28.375 +08:00 [Information] Request starting HTTP/1.1 GET http://localhost:5000/css/style.css  
2017-06-29 11:18:28.411 +08:00 [Information] Request finished in 36.0365ms 404 
2017-06-29 11:18:28.455 +08:00 [Information] Executed action "study.Controllers.ValuesController.yonghuxuzhi (study)" in 3894.8921ms
2017-06-29 11:18:28.471 +08:00 [Information] Request finished in 4010.0556ms 200 text/html; charset=utf-8
2017-06-29 11:19:12.363 +08:00 [Information] "Host","20022","e:\picsig","e:\piclog","e:\pic"------------------------------------
2017-06-29 11:19:13.180 +08:00 [Fatal] Unable to start Kestrel.
System.AggregateException: One or more errors occurred. (Error -4090 EADDRNOTAVAIL address not available) ---> Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvException: Error -4090 EADDRNOTAVAIL address not available
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.Libuv.ThrowError(Int32 statusCode)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.Libuv.tcp_bind(UvTcpHandle handle, SockAddr& addr, Int32 flags)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvTcpHandle.Bind(ServerAddress address)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.TcpListenerPrimary.CreateListenSocket()
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Listener.<StartAsync>b__8_0(Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.ListenerPrimary.<StartAsync>d__12.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.KestrelEngine.CreateServer(ServerAddress address)
   at Microsoft.AspNetCore.Server.Kestrel.KestrelServer.Start[TContext](IHttpApplication`1 application)
---> (Inner Exception #0) Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvException: Error -4090 EADDRNOTAVAIL address not available
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.Libuv.ThrowError(Int32 statusCode)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.Libuv.tcp_bind(UvTcpHandle handle, SockAddr& addr, Int32 flags)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvTcpHandle.Bind(ServerAddress address)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.TcpListenerPrimary.CreateListenSocket()
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Listener.<StartAsync>b__8_0(Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.ListenerPrimary.<StartAsync>d__12.MoveNext()<---

2017-06-29 11:25:31.085 +08:00 [Information] "Host","20022","e:\picsig","e:\piclog","e:\pic"------------------------------------
2017-06-29 11:25:33.076 +08:00 [Information] Request starting HTTP/1.1 GET http://localhost:5000/  
2017-06-29 11:25:33.687 +08:00 [Information] Request finished in 602.7411ms 404 
2017-06-29 11:25:33.756 +08:00 [Information] Request starting HTTP/1.1 GET http://localhost:5000/  
2017-06-29 11:25:33.762 +08:00 [Information] Request finished in 6.7227ms 404 
2017-06-29 11:25:38.282 +08:00 [Information] Request starting HTTP/1.1 GET http://localhost:5000/index  
2017-06-29 11:25:38.432 +08:00 [Information] Executing action method "study.Controllers.ValuesController.Index (study)" with arguments (null) - ModelState is Valid
2017-06-29 11:25:40.720 +08:00 [Information] Executing ViewResult, running view at path "/Views/Values/Index.cshtml".
2017-06-29 11:25:40.880 +08:00 [Information] User profile is available. Using '"C:\Users\Administrator\AppData\Local\ASP.NET\DataProtection-Keys"' as key repository and Windows DPAPI to encrypt keys at rest.
2017-06-29 11:25:41.043 +08:00 [Information] Executed action "study.Controllers.ValuesController.Index (study)" in 2655.9392ms
2017-06-29 11:25:41.093 +08:00 [Information] Request finished in 2801.8799ms 200 text/html; charset=utf-8
2017-06-29 11:36:10.161 +08:00 [Information] "Host","20022","e:\picsig","e:\piclog","e:\pic"------------------------------------
2017-06-29 11:36:12.285 +08:00 [Information] Request starting HTTP/1.1 GET http://localhost:5000/  
2017-06-29 11:36:12.837 +08:00 [Information] Request finished in 545.1879ms 404 
2017-06-29 11:36:12.877 +08:00 [Information] Request starting HTTP/1.1 GET http://localhost:5000/  
2017-06-29 11:36:12.882 +08:00 [Information] Request finished in 5.0386ms 404 
2017-06-29 11:36:19.364 +08:00 [Information] Request starting HTTP/1.1 GET http://localhost:5000/favicon.ico  
2017-06-29 11:36:19.367 +08:00 [Information] Request finished in 3.477ms 404 
2017-06-29 11:36:20.212 +08:00 [Information] Request starting HTTP/1.1 GET http://localhost:5000/index  
2017-06-29 11:36:20.372 +08:00 [Information] Executing action method "study.Controllers.ValuesController.Index (study)" with arguments (null) - ModelState is Valid
2017-06-29 11:36:23.263 +08:00 [Information] Executing ViewResult, running view at path "/Views/Values/Index.cshtml".
2017-06-29 11:36:23.669 +08:00 [Information] User profile is available. Using '"C:\Users\Administrator\AppData\Local\ASP.NET\DataProtection-Keys"' as key repository and Windows DPAPI to encrypt keys at rest.
2017-06-29 11:36:23.863 +08:00 [Information] Executed action "study.Controllers.ValuesController.Index (study)" in 3550.6095ms
2017-06-29 11:36:23.914 +08:00 [Information] Request finished in 3701.7105ms 200 text/html; charset=utf-8
2017-06-29 11:36:30.175 +08:00 [Information] Request starting HTTP/1.1 GET http://localhost:5000/yonghuxuzhi  
2017-06-29 11:36:30.183 +08:00 [Information] Executing action method "study.Controllers.ValuesController.yonghuxuzhi (study)" with arguments (null) - ModelState is Valid
2017-06-29 11:36:30.311 +08:00 [Information] Executing ViewResult, running view at path "/Views/Values/yonghuxuzhi.cshtml".
2017-06-29 11:36:30.323 +08:00 [Information] Executed action "study.Controllers.ValuesController.yonghuxuzhi (study)" in 139.5957ms
2017-06-29 11:36:30.329 +08:00 [Information] Request finished in 154.2613ms 200 text/html; charset=utf-8
2017-06-29 11:36:30.350 +08:00 [Information] Request starting HTTP/1.1 GET http://localhost:5000/css/style.css  
2017-06-29 11:36:30.354 +08:00 [Information] Request finished in 3.895ms 404 
2017-06-29 11:40:54.126 +08:00 [Information] "Host","20022","e:\picsig","e:\piclog","e:\pic"------------------------------------
2017-06-29 11:40:56.209 +08:00 [Information] Request starting HTTP/1.1 GET http://localhost:5000/  
2017-06-29 11:40:56.760 +08:00 [Information] Request finished in 534.9223ms 404 
2017-06-29 11:40:56.810 +08:00 [Information] Request starting HTTP/1.1 GET http://localhost:5000/  
2017-06-29 11:40:56.815 +08:00 [Information] Request finished in 5.3217ms 404 
2017-06-29 11:41:04.394 +08:00 [Information] Request starting HTTP/1.1 GET http://localhost:5000/index  
2017-06-29 11:41:04.562 +08:00 [Information] Executing action method "study.Controllers.ValuesController.Index (study)" with arguments (null) - ModelState is Valid
2017-06-29 11:41:06.937 +08:00 [Information] Executing ViewResult, running view at path "/Views/Values/Index.cshtml".
2017-06-29 11:41:07.087 +08:00 [Information] User profile is available. Using '"C:\Users\Administrator\AppData\Local\ASP.NET\DataProtection-Keys"' as key repository and Windows DPAPI to encrypt keys at rest.
2017-06-29 11:41:07.295 +08:00 [Information] Executed action "study.Controllers.ValuesController.Index (study)" in 2749.1251ms
2017-06-29 11:41:07.392 +08:00 [Information] Request finished in 2998.6404ms 200 text/html; charset=utf-8
2017-06-29 11:41:13.871 +08:00 [Information] Request starting HTTP/1.1 GET http://localhost:5000/yonghuxuzhi  
2017-06-29 11:41:13.881 +08:00 [Information] Executing action method "study.Controllers.ValuesController.Yonghuxuzhi (study)" with arguments (null) - ModelState is Valid
2017-06-29 11:41:14.023 +08:00 [Information] Executing ViewResult, running view at path "/Views/Values/Yonghuxuzhi.cshtml".
2017-06-29 11:41:14.034 +08:00 [Information] Executed action "study.Controllers.ValuesController.Yonghuxuzhi (study)" in 153.1556ms
2017-06-29 11:41:14.040 +08:00 [Information] Request finished in 169.7457ms 200 text/html; charset=utf-8
2017-06-29 11:41:14.059 +08:00 [Information] Request starting HTTP/1.1 GET http://localhost:5000/css/style.css  
2017-06-29 11:41:14.110 +08:00 [Information] Request finished in 51.0159ms 404 
2017-06-29 11:41:44.255 +08:00 [Information] "Host","20022","e:\picsig","e:\piclog","e:\pic"------------------------------------
2017-06-29 11:41:45.020 +08:00 [Fatal] Unable to start Kestrel.
System.AggregateException: One or more errors occurred. (Error -4090 EADDRNOTAVAIL address not available) ---> Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvException: Error -4090 EADDRNOTAVAIL address not available
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.Libuv.ThrowError(Int32 statusCode)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.Libuv.tcp_bind(UvTcpHandle handle, SockAddr& addr, Int32 flags)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvTcpHandle.Bind(ServerAddress address)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.TcpListenerPrimary.CreateListenSocket()
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Listener.<StartAsync>b__8_0(Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.ListenerPrimary.<StartAsync>d__12.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.KestrelEngine.CreateServer(ServerAddress address)
   at Microsoft.AspNetCore.Server.Kestrel.KestrelServer.Start[TContext](IHttpApplication`1 application)
---> (Inner Exception #0) Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvException: Error -4090 EADDRNOTAVAIL address not available
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.Libuv.ThrowError(Int32 statusCode)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.Libuv.tcp_bind(UvTcpHandle handle, SockAddr& addr, Int32 flags)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvTcpHandle.Bind(ServerAddress address)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.TcpListenerPrimary.CreateListenSocket()
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Listener.<StartAsync>b__8_0(Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.ListenerPrimary.<StartAsync>d__12.MoveNext()<---

2017-06-29 11:45:15.004 +08:00 [Information] "Host","20022","e:\picsig","e:\piclog","e:\pic"------------------------------------
2017-06-29 11:45:17.051 +08:00 [Information] Request starting HTTP/1.1 GET http://localhost:5000/  
2017-06-29 11:45:17.549 +08:00 [Information] Request finished in 519.9342ms 404 
2017-06-29 11:45:17.619 +08:00 [Information] Request starting HTTP/1.1 GET http://localhost:5000/  
2017-06-29 11:45:17.625 +08:00 [Information] Request finished in 5.9576ms 404 
2017-06-29 11:45:21.365 +08:00 [Information] Request starting HTTP/1.1 GET http://localhost:5000/index  
2017-06-29 11:45:21.535 +08:00 [Information] Executing action method "study.Controllers.ValuesController.Index (study)" with arguments (null) - ModelState is Valid
2017-06-29 11:45:23.958 +08:00 [Information] Executing ViewResult, running view at path "/Views/Values/Index.cshtml".
2017-06-29 11:45:24.131 +08:00 [Information] User profile is available. Using '"C:\Users\Administrator\AppData\Local\ASP.NET\DataProtection-Keys"' as key repository and Windows DPAPI to encrypt keys at rest.
2017-06-29 11:45:24.348 +08:00 [Information] Request starting HTTP/1.1 GET http://localhost:5000/css/style.css  
2017-06-29 11:45:24.372 +08:00 [Information] Request finished in 24.7709ms 404 
2017-06-29 11:45:24.623 +08:00 [Information] Executed action "study.Controllers.ValuesController.Index (study)" in 3134.6167ms
2017-06-29 11:45:24.653 +08:00 [Information] Request finished in 3287.2252ms 200 text/html; charset=utf-8
2017-06-29 11:45:50.688 +08:00 [Information] "Host","20022","e:\picsig","e:\piclog","e:\pic"------------------------------------
2017-06-29 11:45:52.110 +08:00 [Fatal] Unable to start Kestrel.
System.AggregateException: One or more errors occurred. (Error -4090 EADDRNOTAVAIL address not available) ---> Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvException: Error -4090 EADDRNOTAVAIL address not available
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.Libuv.ThrowError(Int32 statusCode)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.Libuv.tcp_bind(UvTcpHandle handle, SockAddr& addr, Int32 flags)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvTcpHandle.Bind(ServerAddress address)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.TcpListenerPrimary.CreateListenSocket()
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Listener.<StartAsync>b__8_0(Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.ListenerPrimary.<StartAsync>d__12.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.KestrelEngine.CreateServer(ServerAddress address)
   at Microsoft.AspNetCore.Server.Kestrel.KestrelServer.Start[TContext](IHttpApplication`1 application)
---> (Inner Exception #0) Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvException: Error -4090 EADDRNOTAVAIL address not available
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.Libuv.ThrowError(Int32 statusCode)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.Libuv.tcp_bind(UvTcpHandle handle, SockAddr& addr, Int32 flags)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvTcpHandle.Bind(ServerAddress address)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.TcpListenerPrimary.CreateListenSocket()
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Listener.<StartAsync>b__8_0(Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.ListenerPrimary.<StartAsync>d__12.MoveNext()<---

2017-06-29 12:35:31.806 +08:00 [Information] "Host","20022","e:\picsig","e:\piclog","e:\pic"------------------------------------
2017-06-29 12:35:33.116 +08:00 [Fatal] Unable to start Kestrel.
System.AggregateException: One or more errors occurred. (Error -4090 EADDRNOTAVAIL address not available) ---> Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvException: Error -4090 EADDRNOTAVAIL address not available
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.Libuv.ThrowError(Int32 statusCode)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.Libuv.tcp_bind(UvTcpHandle handle, SockAddr& addr, Int32 flags)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvTcpHandle.Bind(ServerAddress address)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.TcpListenerPrimary.CreateListenSocket()
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Listener.<StartAsync>b__8_0(Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.ListenerPrimary.<StartAsync>d__12.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.KestrelEngine.CreateServer(ServerAddress address)
   at Microsoft.AspNetCore.Server.Kestrel.KestrelServer.Start[TContext](IHttpApplication`1 application)
---> (Inner Exception #0) Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvException: Error -4090 EADDRNOTAVAIL address not available
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.Libuv.ThrowError(Int32 statusCode)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.Libuv.tcp_bind(UvTcpHandle handle, SockAddr& addr, Int32 flags)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvTcpHandle.Bind(ServerAddress address)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.TcpListenerPrimary.CreateListenSocket()
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Listener.<StartAsync>b__8_0(Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.ListenerPrimary.<StartAsync>d__12.MoveNext()<---

2017-06-29 13:44:05.735 +08:00 [Information] "Host","20022","e:\picsig","e:\piclog","e:\pic"------------------------------------
2017-06-29 13:44:07.643 +08:00 [Information] Request starting HTTP/1.1 GET http://localhost:5000/  
2017-06-29 13:44:08.093 +08:00 [Information] Request finished in 477.1256ms 404 
2017-06-29 13:44:08.117 +08:00 [Information] Request starting HTTP/1.1 GET http://localhost:5000/  
2017-06-29 13:44:08.121 +08:00 [Information] Request finished in 3.2879ms 404 
2017-06-29 13:44:22.839 +08:00 [Information] Request starting HTTP/1.1 GET http://localhost:5000/index  
2017-06-29 13:44:22.968 +08:00 [Information] Executing action method "study.Controllers.ValuesController.Index (study)" with arguments (null) - ModelState is Valid
2017-06-29 13:44:24.621 +08:00 [Information] Executing ViewResult, running view at path "/Views/Values/Index.cshtml".
2017-06-29 13:44:24.756 +08:00 [Information] User profile is available. Using '"C:\Users\Administrator\AppData\Local\ASP.NET\DataProtection-Keys"' as key repository and Windows DPAPI to encrypt keys at rest.
2017-06-29 13:44:24.838 +08:00 [Information] Request starting HTTP/1.1 GET http://localhost:5000/css/style.css  
2017-06-29 13:44:24.844 +08:00 [Information] Request finished in 6.4155ms 404 
2017-06-29 13:44:24.860 +08:00 [Information] Executed action "study.Controllers.ValuesController.Index (study)" in 1945.5176ms
2017-06-29 13:44:24.896 +08:00 [Information] Request finished in 2058.2696ms 200 text/html; charset=utf-8
2017-06-29 13:44:57.465 +08:00 [Information] "Host","20022","e:\picsig","e:\piclog","e:\pic"------------------------------------
2017-06-29 13:44:58.403 +08:00 [Fatal] Unable to start Kestrel.
System.AggregateException: One or more errors occurred. (Error -4090 EADDRNOTAVAIL address not available) ---> Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvException: Error -4090 EADDRNOTAVAIL address not available
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.Libuv.ThrowError(Int32 statusCode)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.Libuv.tcp_bind(UvTcpHandle handle, SockAddr& addr, Int32 flags)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvTcpHandle.Bind(ServerAddress address)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.TcpListenerPrimary.CreateListenSocket()
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Listener.<StartAsync>b__8_0(Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.ListenerPrimary.<StartAsync>d__12.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.KestrelEngine.CreateServer(ServerAddress address)
   at Microsoft.AspNetCore.Server.Kestrel.KestrelServer.Start[TContext](IHttpApplication`1 application)
---> (Inner Exception #0) Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvException: Error -4090 EADDRNOTAVAIL address not available
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.Libuv.ThrowError(Int32 statusCode)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.Libuv.tcp_bind(UvTcpHandle handle, SockAddr& addr, Int32 flags)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvTcpHandle.Bind(ServerAddress address)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.TcpListenerPrimary.CreateListenSocket()
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Listener.<StartAsync>b__8_0(Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.ListenerPrimary.<StartAsync>d__12.MoveNext()<---

2017-06-29 14:49:50.117 +08:00 [Information] "Host","20022","e:\picsig","e:\piclog","e:\pic"------------------------------------
2017-06-29 14:49:53.044 +08:00 [Information] Request starting HTTP/1.1 GET http://localhost:5000/  
2017-06-29 14:49:53.473 +08:00 [Information] Request finished in 459.9126ms 404 
2017-06-29 14:49:53.509 +08:00 [Information] Request starting HTTP/1.1 GET http://localhost:5000/  
2017-06-29 14:49:53.514 +08:00 [Information] Request finished in 4.9305ms 404 
2017-06-29 14:50:17.878 +08:00 [Information] "Host","20022","e:\picsig","e:\piclog","e:\pic"------------------------------------
2017-06-29 14:50:18.742 +08:00 [Fatal] Unable to start Kestrel.
System.AggregateException: One or more errors occurred. (Error -4090 EADDRNOTAVAIL address not available) ---> Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvException: Error -4090 EADDRNOTAVAIL address not available
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.Libuv.ThrowError(Int32 statusCode)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.Libuv.tcp_bind(UvTcpHandle handle, SockAddr& addr, Int32 flags)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvTcpHandle.Bind(ServerAddress address)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.TcpListenerPrimary.CreateListenSocket()
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Listener.<StartAsync>b__8_0(Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.ListenerPrimary.<StartAsync>d__12.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.KestrelEngine.CreateServer(ServerAddress address)
   at Microsoft.AspNetCore.Server.Kestrel.KestrelServer.Start[TContext](IHttpApplication`1 application)
---> (Inner Exception #0) Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvException: Error -4090 EADDRNOTAVAIL address not available
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.Libuv.ThrowError(Int32 statusCode)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.Libuv.tcp_bind(UvTcpHandle handle, SockAddr& addr, Int32 flags)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvTcpHandle.Bind(ServerAddress address)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.TcpListenerPrimary.CreateListenSocket()
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Listener.<StartAsync>b__8_0(Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.ListenerPrimary.<StartAsync>d__12.MoveNext()<---

2017-06-29 14:50:29.148 +08:00 [Information] "Host","20022","e:\picsig","e:\piclog","e:\pic"------------------------------------
2017-06-29 14:50:29.932 +08:00 [Fatal] Unable to start Kestrel.
System.AggregateException: One or more errors occurred. (Error -4090 EADDRNOTAVAIL address not available) ---> Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvException: Error -4090 EADDRNOTAVAIL address not available
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.Libuv.ThrowError(Int32 statusCode)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.Libuv.tcp_bind(UvTcpHandle handle, SockAddr& addr, Int32 flags)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvTcpHandle.Bind(ServerAddress address)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.TcpListenerPrimary.CreateListenSocket()
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Listener.<StartAsync>b__8_0(Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.ListenerPrimary.<StartAsync>d__12.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.KestrelEngine.CreateServer(ServerAddress address)
   at Microsoft.AspNetCore.Server.Kestrel.KestrelServer.Start[TContext](IHttpApplication`1 application)
---> (Inner Exception #0) Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvException: Error -4090 EADDRNOTAVAIL address not available
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.Libuv.ThrowError(Int32 statusCode)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.Libuv.tcp_bind(UvTcpHandle handle, SockAddr& addr, Int32 flags)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvTcpHandle.Bind(ServerAddress address)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.TcpListenerPrimary.CreateListenSocket()
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Listener.<StartAsync>b__8_0(Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.ListenerPrimary.<StartAsync>d__12.MoveNext()<---

2017-06-29 15:20:21.018 +08:00 [Information] "Host","20022","e:\picsig","e:\piclog","e:\pic"------------------------------------
2017-06-29 15:20:24.081 +08:00 [Information] Request starting HTTP/1.1 GET http://localhost:5000/  
2017-06-29 15:20:24.548 +08:00 [Information] Request finished in 472.9009ms 404 
2017-06-29 15:20:24.582 +08:00 [Information] Request starting HTTP/1.1 GET http://localhost:5000/  
2017-06-29 15:20:24.585 +08:00 [Information] Request finished in 3.3143ms 404 
2017-06-29 15:20:40.137 +08:00 [Information] "Host","20022","e:\picsig","e:\piclog","e:\pic"------------------------------------
2017-06-29 15:20:41.215 +08:00 [Fatal] Unable to start Kestrel.
System.AggregateException: One or more errors occurred. (Error -4090 EADDRNOTAVAIL address not available) ---> Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvException: Error -4090 EADDRNOTAVAIL address not available
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.Libuv.ThrowError(Int32 statusCode)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.Libuv.tcp_bind(UvTcpHandle handle, SockAddr& addr, Int32 flags)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvTcpHandle.Bind(ServerAddress address)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.TcpListenerPrimary.CreateListenSocket()
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Listener.<StartAsync>b__8_0(Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.ListenerPrimary.<StartAsync>d__12.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.KestrelEngine.CreateServer(ServerAddress address)
   at Microsoft.AspNetCore.Server.Kestrel.KestrelServer.Start[TContext](IHttpApplication`1 application)
---> (Inner Exception #0) Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvException: Error -4090 EADDRNOTAVAIL address not available
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.Libuv.ThrowError(Int32 statusCode)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.Libuv.tcp_bind(UvTcpHandle handle, SockAddr& addr, Int32 flags)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvTcpHandle.Bind(ServerAddress address)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.TcpListenerPrimary.CreateListenSocket()
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Listener.<StartAsync>b__8_0(Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.ListenerPrimary.<StartAsync>d__12.MoveNext()<---

2017-06-29 15:52:29.461 +08:00 [Information] "Host","20022","e:\picsig","e:\piclog","e:\pic"------------------------------------
2017-06-29 15:52:33.314 +08:00 [Information] Request starting HTTP/1.1 GET http://localhost:5000/  
2017-06-29 15:52:34.053 +08:00 [Information] Request finished in 799.584ms 404 
2017-06-29 15:52:34.103 +08:00 [Information] Request starting HTTP/1.1 GET http://localhost:5000/  
2017-06-29 15:52:34.141 +08:00 [Information] Request finished in 38.3ms 404 
2017-06-29 15:53:09.076 +08:00 [Information] "Host","20022","e:\picsig","e:\piclog","e:\pic"------------------------------------
2017-06-29 15:53:10.178 +08:00 [Fatal] Unable to start Kestrel.
System.AggregateException: One or more errors occurred. (Error -4090 EADDRNOTAVAIL address not available) ---> Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvException: Error -4090 EADDRNOTAVAIL address not available
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.Libuv.ThrowError(Int32 statusCode)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.Libuv.tcp_bind(UvTcpHandle handle, SockAddr& addr, Int32 flags)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvTcpHandle.Bind(ServerAddress address)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.TcpListenerPrimary.CreateListenSocket()
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Listener.<StartAsync>b__8_0(Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.ListenerPrimary.<StartAsync>d__12.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.KestrelEngine.CreateServer(ServerAddress address)
   at Microsoft.AspNetCore.Server.Kestrel.KestrelServer.Start[TContext](IHttpApplication`1 application)
---> (Inner Exception #0) Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvException: Error -4090 EADDRNOTAVAIL address not available
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.Libuv.ThrowError(Int32 statusCode)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.Libuv.tcp_bind(UvTcpHandle handle, SockAddr& addr, Int32 flags)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvTcpHandle.Bind(ServerAddress address)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.TcpListenerPrimary.CreateListenSocket()
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Listener.<StartAsync>b__8_0(Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.ListenerPrimary.<StartAsync>d__12.MoveNext()<---

2017-06-29 16:24:22.150 +08:00 [Information] "Host","20022","e:\picsig","e:\piclog","e:\pic"------------------------------------
2017-06-29 16:24:24.720 +08:00 [Information] Request starting HTTP/1.1 GET http://localhost:5000/  
2017-06-29 16:24:25.169 +08:00 [Information] Request finished in 469.5435ms 404 
2017-06-29 16:24:25.199 +08:00 [Information] Request starting HTTP/1.1 GET http://localhost:5000/  
2017-06-29 16:24:25.202 +08:00 [Information] Request finished in 3.1576ms 404 
2017-06-29 16:24:56.638 +08:00 [Information] "Host","20022","e:\picsig","e:\piclog","e:\pic"------------------------------------
2017-06-29 16:24:57.550 +08:00 [Fatal] Unable to start Kestrel.
System.AggregateException: One or more errors occurred. (Error -4090 EADDRNOTAVAIL address not available) ---> Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvException: Error -4090 EADDRNOTAVAIL address not available
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.Libuv.ThrowError(Int32 statusCode)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.Libuv.tcp_bind(UvTcpHandle handle, SockAddr& addr, Int32 flags)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvTcpHandle.Bind(ServerAddress address)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.TcpListenerPrimary.CreateListenSocket()
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Listener.<StartAsync>b__8_0(Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.ListenerPrimary.<StartAsync>d__12.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.KestrelEngine.CreateServer(ServerAddress address)
   at Microsoft.AspNetCore.Server.Kestrel.KestrelServer.Start[TContext](IHttpApplication`1 application)
---> (Inner Exception #0) Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvException: Error -4090 EADDRNOTAVAIL address not available
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.Libuv.ThrowError(Int32 statusCode)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.Libuv.tcp_bind(UvTcpHandle handle, SockAddr& addr, Int32 flags)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvTcpHandle.Bind(ServerAddress address)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.TcpListenerPrimary.CreateListenSocket()
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Listener.<StartAsync>b__8_0(Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.ListenerPrimary.<StartAsync>d__12.MoveNext()<---

2017-06-29 17:14:34.367 +08:00 [Information] "Host","20022","e:\picsig","e:\piclog","e:\pic"------------------------------------
2017-06-29 17:14:37.026 +08:00 [Information] Request starting HTTP/1.1 GET http://localhost:5000/  
2017-06-29 17:14:37.489 +08:00 [Information] Request finished in 487.9218ms 404 
2017-06-29 17:14:37.510 +08:00 [Information] Request starting HTTP/1.1 GET http://localhost:5000/  
2017-06-29 17:14:37.516 +08:00 [Information] Request finished in 6.1349ms 404 
2017-06-29 17:15:16.705 +08:00 [Information] "Host","20022","e:\picsig","e:\piclog","e:\pic"------------------------------------
2017-06-29 17:15:17.517 +08:00 [Fatal] Unable to start Kestrel.
System.AggregateException: One or more errors occurred. (Error -4090 EADDRNOTAVAIL address not available) ---> Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvException: Error -4090 EADDRNOTAVAIL address not available
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.Libuv.ThrowError(Int32 statusCode)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.Libuv.tcp_bind(UvTcpHandle handle, SockAddr& addr, Int32 flags)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvTcpHandle.Bind(ServerAddress address)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.TcpListenerPrimary.CreateListenSocket()
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Listener.<StartAsync>b__8_0(Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.ListenerPrimary.<StartAsync>d__12.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.KestrelEngine.CreateServer(ServerAddress address)
   at Microsoft.AspNetCore.Server.Kestrel.KestrelServer.Start[TContext](IHttpApplication`1 application)
---> (Inner Exception #0) Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvException: Error -4090 EADDRNOTAVAIL address not available
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.Libuv.ThrowError(Int32 statusCode)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.Libuv.tcp_bind(UvTcpHandle handle, SockAddr& addr, Int32 flags)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvTcpHandle.Bind(ServerAddress address)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.TcpListenerPrimary.CreateListenSocket()
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Listener.<StartAsync>b__8_0(Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.ListenerPrimary.<StartAsync>d__12.MoveNext()<---

